### ISSUE TITLE
port forwarding in vagrant 1.9.3 on windows systems

### ISSUE THREAD

**Issue by pauloagsantos** [iptomar/projectary-api#12]
in vagrant file, the line:
**config.vm.network :forwarded_port, guest: 80, host:4567**
doesnt work in windows host machines. is an know bug of version 1.9.3.

the oficial solution is to roolback to version 1.9.2 or change the line to:
**config.vm.network "forwarded_port", guest: 8080, host: 4567, host_ip: "127.0.0.1"**

**Comment by asantos3** [comment]
I got no problem by running `vagrant up`, and `npm install`, on a shell with admin rights. It might be needed to delete the VM and create a new one.

Does that work?

**Comment by rui1974** [comment]
ports forwarded on current vagrant file 8080 -> 8080 ; 3306 -> 33060 . Destroy any Vagrant you have and rebuid

**Comment by asantos3** [comment]
The new vagrantfile works great on `1.9.2`. Using both `1.9.3` and `1.9.4` gives different errors.

Uninstall the current vagrant (no need to restart), [download the 1.9.2](https://releases.hashicorp.com/vagrant/1.9.2/) and restart.

Should work and hopefully 1.9.5 comes soon because the fix for the 1.9.4 error is already merged upstream.
